### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by avdeev** [Radivarig/react-infinite-any-height#2]
Warning: React.__spread is deprecated and should not be used. Use Object.assign directly or another helper function with similar semantics. You may be seeing this warning due to your compiler. See https://fb.me/react-spread-deprecation for more details.printWarning @

Warning: a `span` tag (owner: `GetHeightWrapper`) was passed a numeric string value for CSS property `content` (value: ` `) which will be treated as a unitless number in a future version of React.

**Comment by Radivarig** [comment]
Hi, this is because of `jsx-loader`, which is not maintained anymore. I'll switch it with `babel-loader` soon.

**Comment by DimitryDushkin** [comment]
Up =)

**Comment by DimitryDushkin** [comment]
I've done this, but in gist https://gist.github.com/DimitryDushkin/414f40e3fdd12288ca4ff4e6e2e57620

We'll try to make real PR.)

**Comment by Radivarig** [comment]
Merged #6
