### ISSUE TITLE
What to pass for scrollContainer?

### ISSUE THREAD

**Issue by melchoir55** [Radivarig/react-infinite-any-height#9]
It isn't clear what to pass to the `scrollContainer  `prop. Can you please provide example code exercising this prop?

For reference, I'm passing this:

```
<div className="col-9" ref="scrollContainer">
      <InfiniteAnyHeight
        list={this.state.messageCards}
        containerHeight={500}
        scrollContainer={this.refs.scrollContainer}
        displayBottomUpwards>

      </InfiniteAnyHeight>
</div>
```

Which throws: `Uncaught TypeError: Cannot read property 'scrollTop' of undefined`

**Comment by melchoir55** [comment]
I got this working. For anyone coming across this, the code I pasted above works, but it is important that it is part of the render directly. I was inserting the code using a method, and I'm pretty sure that meant that when it was getting created initially there was no reference for ref to latch on to.

**Comment by jcgertig** [comment]
@melchoir55 please close the issue
